// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bSDSGATujDWaJhRdI6_ms-c0nJizJGA',
    appId: '1:207335230332:android:5f5e4eb747b14b1b0bf2f9',
    messagingSenderId: '207335230332',
    projectId: 'testingflutterapp-5b65e',
    databaseURL: 'https://testingflutterapp-5b65e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testingflutterapp-5b65e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-KbHg4o-z6vdrGeXvSHXUMly9KJXlxEk',
    appId: '1:207335230332:ios:9b834ccfbe1ffd840bf2f9',
    messagingSenderId: '207335230332',
    projectId: 'testingflutterapp-5b65e',
    databaseURL: 'https://testingflutterapp-5b65e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testingflutterapp-5b65e.appspot.com',
    iosClientId: '207335230332-s2eu1kuvbqca36gvemle8e3gqhu3rjqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushNotificationss',
  );
}
